### ISSUE TITLE
Stix 2.0 import/export problems after updating to v2.4.102

### ISSUE THREAD

**Issue by faimario** [MISP/MISP#4107]
### Work environment

| Questions                 | Answers
|---------------------------|--------------------
| Type of issue             | Bug
| OS version (server)       | ubuntu
| OS version (client)       | Seven
| PHP version               | 7.0.22
| MISP version    | 2.4.102

### Expected behavior
Import STIX 2.0 Document using STIX 2.0 Import tool
Export a stored MISP event in STIX 2.0 format through STIX 2.0 Export tool

### Actual behavior
**Import case:** When trying importing a valid STIX 2.0 sample, following error is obtained: 
Could not import STIX document: Issues executing the ingestion script or invalid input. Please check whether the dependencies for STIX are met via the diagnostic tool. 
**Export case:** When trying downloading a stored MISP event, I am redirected to a blank page and the file is actually not downloaded.

Diagnostic tool does not detect any kind of errors, in both cases

### Steps to reproduce the behavior
**Import case:** Try to import a valid STIX 2.0 sample through Import from...--> STIX 2.0 format (lossy)
**Export case:** Try to export a MISP event through Download as...--> STIX 2.0 (requires STIX 2.0 libraries)

### Logs, screenshots, configuration dump, ...
**Import case:**
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1421, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/stix2misp.py", line 1391, in main
    event = stix2.parse(f.read(), allow_custom=True, interoperability=True)
TypeError: parse() got an unexpected keyword argument 'interoperability'
tail: exec-errors.log: file truncated
**Export case:** exec-errors.log 
Traceback (most recent call last):
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1258, in <module>
    main(sys.argv)
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 1255, in main
    stix_builder.buildEvent()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 58, in buildEvent
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 58, in <listcomp>
    stix_packages = [sdo for event in self.json_event['response'] for sdo in self.handler(event['Event'])] if self.json_event.get('response') else self.handler(self.json_event['Event'])
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 146, in handler
    i = self.__set_identity()
  File "/var/www/MISP/app/files/scripts/stix2/misp2stix2.py", line 125, in __set_identity
    identity_class="organization", interoperability=True)
  File "/usr/local/lib/python3.5/dist-packages/stix2/base.py", line 141, in __init__
    raise ExtraPropertiesError(cls, extra_kwargs)
stix2.exceptions.ExtraPropertiesError: Unexpected properties for Identity: (interoperability).

I experienced this error after updating from v2.4.93 to v2.4.102. Before, both export and import were working fine.

**Comment by chrisr3d** [comment]
I am currently working on a script to update the python dependencies using a python virtual environment, but for now the issue you have is due to some recent changes we added to the python stix2 library.

What you can do is:
`cd` _`${YOUR_PATH_TO_MISP}`_
`git pull origin 2.4`
`git submodule sync`
`git submodule update`
`cd cti-python-stix2`
`pip3 install -I .`

It should work for the moment until the update script is released.

Then you can also check with the diagnostic tool if you have the right stix2 library version.

**Comment by faimario** [comment]
Thank you very much, I confirm that now STIX import/export is working fine. Also the diagnostic tool is not detecting any permissions or dependencies issue.

However, I have a new problem, which i don't know if it is related or not.
In the Home Page, where all events are shown, tags for each events are visible, but i cannot add new ones. 

Besides, which is more weird, every time I want to check the details of an event ('View Event' button), many information (e.g., tags, if it is published or not,...) are not displayed.
Just Event Id, UUID, Source and Member Organisation are displayed. For instance, I cannot even display or add tags. 

Attributes, instead, are shown correctly and i can add all the tags I want to each of them (MISP taxonomies are all available).

Before following these steps I was able to display all the details, associated to an event, correctly. My version was always 2.4.102.

**Comment by RichieB2B** [comment]
I had to do a `git submodule sync` before the update worked. After that the `pip3 install` dumps core. :-( This is on Ubuntu 18.04.02 LTS.
```
# pip3 install -I .
Processing /var/www/MISP/cti-python-stix2
Collecting python-dateutil (from stix2==1.1.1)
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting pytz (from stix2==1.1.1)
  Using cached https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl
Collecting requests (from stix2==1.1.1)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting simplejson (from stix2==1.1.1)
Collecting six (from stix2==1.1.1)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting stix2-patterns (from stix2==1.1.1)
  Using cached https://files.pythonhosted.org/packages/c9/95/2ed814e9d93110b10b7afade3c53358618d3121f184f83b935e900b38f9e/stix2_patterns-1.1.0-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests->stix2==1.1.1)
  Using cached https://files.pythonhosted.org/packages/9f/e0/accfc1b56b57e9750eba272e24c4dddeac86852c2bebd1236674d7887e8a/certifi-2018.11.29-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests->stix2==1.1.1)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests->stix2==1.1.1)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests->stix2==1.1.1)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting antlr4-python3-runtime>=4.7; python_version >= "3" (from stix2-patterns->stix2==1.1.1)
Building wheels for collected packages: stix2
  Running setup.py bdist_wheel for stix2 ... done
  Stored in directory: /root/.cache/pip/wheels/56/53/71/3082949580400d343ff20c4736be4b14e7bb05f3d18afb4160
Successfully built stix2
Installing collected packages: six, python-dateutil, pytz, certifi, chardet, idna, urllib3, requests, simplejson, antlr4-python3-runtime, stix2-patterns, stix2
Successfully installed antlr4-python3-runtime-4.7.2 certifi-2018.11.29 chardet-3.0.4 idna-2.8 python-dateutil-2.8.0 pytz-2018.9 requests-2.21.0 simplejson-3.16.0 six-1.12.0 stix2-1.1.1 stix2-patterns-1.1.0 urllib3-1.24.1
Segmentation fault (core dumped)
```

**Comment by SteveClement** [comment]
re-open with more details in case not fixed. (or not related)

**Comment by pettai** [comment]
as a side note: I see the same with the latest MISP (2.4.132) and while using the REST client
And unfortunately, there aren't any logs generated. (I also got the same segmentation fault while upgrading cti-python-stix2)

**Comment by adulau** [comment]
@pettai Thanks for the info. What's your version of Python and pip ? I remember some issues with older version of Python 3/pip.

**Comment by pettai** [comment]
It's Python3.6 supplied by Ubuntu 18.04 (just like this PR reports). 

strange enough, installing misp_stix_converter made it work for me!

`pip3 install misp_stix_converter`

is there a missing python dep for MISP stix2 REST API somewhere?

`Installing collected packages: pyaml, nose, libtaxii, colorlog, orderedmultidict, furl, cabby, misp-stix-converter
Successfully installed cabby-0.1.20 colorlog-4.2.1 furl-2.1.0 libtaxii-1.1.117 misp-stix-converter-0.2.11 nose-1.3.7 orderedmultidict-1.0.1 pyaml-20.4.0`

(yes I know, Python3.6 is deprecated as of 2020, just trying to keep the oldest MISP instance alive a little longer before migrating/upgrading...)
