### ISSUE TITLE
STIX Export Error After MISP Update (2.4.74)

### ISSUE THREAD

**Issue by iamshleya** [MISP/MISP#2238]
This issue is related to issue 2181

We updated our instance to STIX v1.2.0.4. After attempting to export an event in STIX format, we received "An internal error has occurred."

After doing some troubleshooting locally on the machine, we received the following errors. We have mixbox installed and there are no errors on any of the imports.

>>> from mixbox import idgen
>>> from cybox.utils import Namespace
>>> from mixbox import idgen
>>> stix.utils.idgen.set_id_namespace({'test' : 'test2' })
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**AttributeError: 'module' object has no attribute 'idgen'**

Looking at the code under the misp2stix_framing.py, it does not look like it accounts for an attribute error...

    try:
        stix.utils.idgen.set_id_namespace({baseURL: orgname})
    **except ValueError:**
        # Some weird stix error that sometimes occurs if the stars
        # align and Mixbox is being mean to us
        # Glory to STIX, peace and good xmlns be upon it
        try:
            idgen.set_id_namespace(Namespace(baseURL, orgname))
        **except TypeError:**
            # Ok this only occurs if the script is being run under py3
            # and if we're running a REALLY weird version of stix
            # May as well catch it
            idgen.set_id_namespace(Namespace(baseURL, orgname, "MISP"))

Even though the code failed prior to reaching the exceptions, we tested the logic, and it also looks like that would fail as well.

>>> idgen.set_id_namespace(Namespace('test1', 'test2'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/mixbox-1.0.2-py2.7.egg/mixbox/idgen.py", line 97, in set_id_namespace
    _get_generator().namespace = namespace
  File "/usr/lib/python2.7/site-packages/mixbox-1.0.2-py2.7.egg/mixbox/idgen.py", line 46, in namespace
    raise ValueError("Must be a Namespace object")
**ValueError: Must be a Namespace object**
>>> idgen.set_id_namespace(Namespace('test1', 'test2', "MISP"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/mixbox-1.0.2-py2.7.egg/mixbox/idgen.py", line 97, in set_id_namespace
    _get_generator().namespace = namespace
  File "/usr/lib/python2.7/site-packages/mixbox-1.0.2-py2.7.egg/mixbox/idgen.py", line 46, in namespace
    raise ValueError("Must be a Namespace object")
**ValueError: Must be a Namespace object**

**Comment by adulau** [comment]
We are currently using this version:

~~~~
>>> print json.dumps({'success' : 1, 'stix' : stix.__version__, 'cybox' : cybox.__version__})
{"cybox": "2.1.0.10", "stix": "1.1.1.4", "success": 1}
~~~~

In the meanwhile, could you checkout those version?

We will review the current fixes and what's the best approach to keep the backward and forward compatibility. @FloatingGhost any ideas?

**Comment by FloatingGhost** [comment]
Words cannot describe how much I hate STIX.

I've submitted a PR that *SHOULD*™® fix this rather bizarre issue.

Can someone go shout at the STIX people and tell them to stop moving things around in patch releases

**Comment by FloatingGhost** [comment]
Oh and I guess I have to continue my little crusade

# ***STOP USING PYTHON2***

**Comment by adulau** [comment]
@FloatingGhost ;-) We'll live with the dead for a long period... 

@iamshleya Could you test the HEAD? The fix from @FloatingGhost should work and thanks to her.

**Comment by iamshleya** [comment]
Thank you for the quick response! We're still seeing the same internal error from earlier today. Below is some more troubleshooting.

>>> from mixbox import idgen
>>> from cybox.utils import Namespace
>>> **idgen.set_id_namespace({'test': 'test1'})**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/mixbox/idgen.py", line 97, in set_id_namespace
    _get_generator().namespace = namespace
  File "/usr/lib/python3.4/site-packages/mixbox/idgen.py", line 46, in namespace
    raise ValueError("Must be a Namespace object")
**ValueError: Must be a Namespace object**

>>>idgen.set_id_namespace(Namespace('test', 'test1')) -- does not return an error.

When checking /var/log/messages, we're seeing a new error
Earlier today
Jun  1 08:20:47 server python: detected unhandled Python exception in '/var/www/MISP/app/files/scripts**/misp2stix_framing.py'** 
Now
Jun  1 10:28:00 server python: detected unhandled Python exception in '/var/www/MISP/app/files/scripts/**misp2stix.py'**

Potentially related to line 283 in misp2stix.py?
stix.utils.idgen.set_id_namespace({namespace[0]: namespace[1]}) 

>>> stix.utils.idgen.set_id_namespace({'test' : 'test2'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
**AttributeError: 'module' object has no attribute 'idgen'**

Tomorrow I will try downgrading to STIX v1.1.1.4.

**Comment by FloatingGhost** [comment]
I can confidently say that you haven't updated to HEAD

Please update and try again.

**Comment by FloatingGhost** [comment]
I genuinely want to hang myself because of STIX

#2242

**Comment by adulau** [comment]
It's merged (tested with different versions with success). Thanks to @FloatingGhost to keep a sane life-style to avoid any STIX serial killing ;-)

@iamshleya can you pull and try again? Thank you.

**Comment by iamshleya** [comment]
Sorry for continuing to add to the STIX frustration, but we still can't get it to work on both 1.2.0.4 and 1.1.1.4 :( 

v.1.2.0.4

:backtrace:
:misp2stix.py:278:addJournalEntry:AttributeError: 'NoneType' object has no attribute 'append'
:Traceback (most recent call last):
:  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 302, in <module>
:    main(sys.argv)
:  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 297, in main
:    stix_package = generateEventPackage(event)
:  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 79, in generateEventPackage
:    objects = generateSTIXObjects(event)
:  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 91, in generateSTIXObjects
:    addJournalEntry(incident, "Event Threat Level: " + event["ThreatLevel"]["name"])
:  File "/var/www/MISP/app/files/scripts/misp2stix.py", line 278, in addJournalEntry
:    incident.history.append(hi)
:AttributeError: 'NoneType' object has no attribute 'append'
:
:Local variables in innermost frame:
:entry_line: u'Event Threat Level: Low'
:hi: <stix.incident.history.HistoryItem object at 0x3c0b190>
:incident: <stix.incident.Incident object at 0x3c02ad0>


v1.1.1.4

:Traceback (most recent call last):
:  File "/var/www/MISP/app/files/scripts/stixtest.py", line 3, in <module>
:    import stix
:  File "build/bdist.linux-x86_64/egg/stix/__init__.py", line 5, in <module>
:  File "build/bdist.linux-x86_64/egg/stix/base.py", line 11, in <module>
:  File "build/bdist.linux-x86_64/egg/stix/utils/__init__.py", line 388, in <module>
:  File "build/bdist.linux-x86_64/egg/stix/utils/nsparser.py", line 434, in <module>
:AttributeError: 'module' object has no attribute 'NS_LIST'
:Local variables in innermost frame:
:ignored: None
:DuplicatePrefixError: None
:XML_NAMESPACES: None
:stix: None
:warnings: None
:__builtins__: {'bytearray': <type 'bytearray'>, 'IndexError': <type 'exceptions.IndexError'>, 'all': <built-in function all>, 'help': Type help() for interactive help, or help(object) for help about object., 'vars': <built-in function vars>, 'SyntaxError': <type 'exceptions.SyntaxError'>, 'unicode': <type 'unicode'>, 'UnicodeDecodeError': <type 'exceptions.UnicodeDecodeError'>, 'memoryview': <type 'memoryview'>, 'isinstance': <built-in function isinstance>

**Comment by FloatingGhost** [comment]
`:AttributeError: 'module' object has no attribute 'NS_LIST'`

I KNOW THIS ONE!

you're using the pip version of... I think cybox. It doesn't work. 

Try uninstalling stix, cybox, and mixbox and re-installing from their respective git repos.

**Comment by iamshleya** [comment]
Ah, thank you for another quick response. We finally figured out what was going on (at least part of the problem). When we downgraded to version 1.1.1.4, we still had mixbox installed on the server. Since mixbox was still there, it was trying to import the idgen from mixbox instead of from stix.utils, which was causing an error.

Uninstalling mixbox fixed the issue, and we're now able to export in STIX format.
